import type { Courier, Order } from "./types";

const minuteFloor = (ts: number) => Math.floor(ts / 60000) * 60000;

export const buildCouriers = (): Courier[] => [
  { id: "c1", name: "Diego Souza", status: "em_rota" },
  { id: "c2", name: "Larissa Prado", status: "em_rota" },
  { id: "c3", name: "Túlio Ramos", status: "disponivel" },
  { id: "c4", name: "Renata Lima", status: "inativo" },
];

export const buildOrders = (now = Date.now()): Order[] => {
  const ago = (min: number) => minuteFloor(now - min * 60000);

  return [
    {
      id: "ord_9f3a482",
      createdAt: ago(3),
      channel: "delivery",
      customerName: "Marcos Vieira",
      customerPhone: "(11) 98877-0231",
      items: [
        {
          id: "i1",
          qty: 2,
          name: "Combo Kombu",
          subtotal: 64,
          variation: ["Pão de batata", "Carne: Misto"],
          optionals: ["Molho de pimenta", "Alface extra"],
          addons: [{ qty: 1, name: "Bacon extra", subtotal: 8 }],
        },
        { id: "i2", qty: 1, name: "Suco de laranja", subtotal: 12, variation: ["Grande", "Sem açúcar"] },
      ],
      subtotal: 84,
      deliveryFee: 8,
      total: 92,
      payment: { method: "presencial", presentialMethod: "dinheiro", changeFor: 100, paid: false },
      address: {
        street: "Rua das Acácias",
        number: "220",
        complement: "Apto 42",
        neighborhood: "Jardim Norte",
        reference: "Portaria azul, ao lado da farmácia",
      },
      notes: "Sem cebola no sanduíche, por favor. Deixar na portaria.",
      disposables: true,
      status: "recebido",
    },
    {
      id: "ord_2b1c481",
      createdAt: ago(5),
      channel: "balcao",
      balcaoMode: "mesa",
      tableNumber: 7,
      items: [
        { id: "i1", qty: 1, name: "Prato executivo", subtotal: 34, variation: ["Frango grelhado"] },
        { id: "i2", qty: 1, name: "Refrigerante lata", subtotal: 8 },
      ],
      subtotal: 42,
      deliveryFee: 0,
      total: 42,
      payment: { method: "presencial", presentialMethod: "debito", paid: true },
      status: "pago",
    },
    {
      id: "ord_77de480",
      createdAt: ago(7),
      channel: "mesa",
      tableNumber: 12,
      customerName: "João Pereira",
      items: [
        {
          id: "i1",
          qty: 2,
          name: "Burger Clássico",
          subtotal: 58,
          variation: ["Ponto: ao ponto"],
          optionals: ["Maionese da casa"],
        },
        { id: "i2", qty: 1, name: "Batata rústica", subtotal: 18, variation: ["Grande"] },
        { id: "i3", qty: 3, name: "Chopp 300ml", subtotal: 52.5 },
      ],
      subtotal: 128.5,
      deliveryFee: 0,
      total: 128.5,
      payment: { method: "pix", paid: true },
      notes: "Uma das batatas sem sal.",
      status: "recebido",
    },
    {
      id: "ord_a01f478",
      createdAt: ago(12),
      channel: "balcao",
      balcaoMode: "avulso",
      customerName: "Fernanda",
      items: [
        {
          id: "i1",
          qty: 1,
          name: "Salada Kombu",
          subtotal: 32,
          optionals: ["Molho de iogurte"],
          addons: [{ qty: 1, name: "Frango extra", subtotal: 10 }],
        },
        { id: "i2", qty: 1, name: "Água com gás", subtotal: 6 },
        { id: "i3", qty: 1, name: "Brownie", subtotal: 14.4 },
      ],
      subtotal: 62.4,
      deliveryFee: 0,
      total: 62.4,
      payment: { method: "presencial", presentialMethod: "credito", paid: false },
      status: "preparo",
    },
    {
      id: "ord_5c9d476",
      createdAt: ago(16),
      channel: "delivery",
      customerName: "Ana Paula",
      customerPhone: "(11) 97120-4450",
      items: [
        {
          id: "i1",
          qty: 1,
          name: "Pizza Margherita",
          subtotal: 62,
          variation: ["Grande", "Borda recheada"],
          addons: [{ qty: 2, name: "Manjericão extra", subtotal: 6 }],
        },
        { id: "i2", qty: 1, name: "Guaraná 1L", subtotal: 12 },
      ],
      subtotal: 90,
      deliveryFee: 8,
      total: 98,
      payment: { method: "cartao_online", paid: true },
      address: { street: "Av. Paulista", number: "1500", neighborhood: "Bela Vista", reference: "Conjunto 12" },
      disposables: false,
      status: "preparo",
    },
    {
      id: "ord_e44b474",
      createdAt: ago(20),
      channel: "delivery",
      customerName: "Rafael Nunes",
      customerPhone: "(11) 99311-7820",
      items: [
        {
          id: "i1",
          qty: 2,
          name: "Combo Kombu",
          subtotal: 64,
          variation: ["Pão de batata", "Carne: Misto"],
          optionals: ["Molho de pimenta"],
          addons: [{ qty: 1, name: "Bacon extra", subtotal: 8 }],
        },
        { id: "i2", qty: 1, name: "Brownie", subtotal: 14.4, optionals: ["Calda de chocolate"] },
      ],
      subtotal: 86.4,
      deliveryFee: 8,
      total: 94.4,
      payment: { method: "pix", paid: true },
      address: { street: "Rua Harmonia", number: "88", neighborhood: "Vila Madalena", reference: "Casa amarela" },
      notes: "Tocar o interfone 2x.",
      disposables: true,
      status: "pronto",
    },
    {
      id: "ord_1d2e473",
      createdAt: ago(23),
      channel: "balcao",
      balcaoMode: "mesa",
      tableNumber: 3,
      items: [
        { id: "i1", qty: 2, name: "Café coado", subtotal: 12 },
        { id: "i2", qty: 2, name: "Pão de queijo", subtotal: 14 },
        { id: "i3", qty: 1, name: "Bolo de cenoura", subtotal: 10 },
      ],
      subtotal: 36,
      deliveryFee: 0,
      total: 36,
      payment: { method: "presencial", presentialMethod: "voucher", paid: true },
      status: "pronto",
    },
    {
      id: "ord_88aa470",
      createdAt: ago(31),
      channel: "delivery",
      customerName: "Camila Rocha",
      customerPhone: "(11) 96400-1189",
      items: [
        { id: "i1", qty: 3, name: "Yakisoba", subtotal: 96, variation: ["Carne"], optionals: ["Shoyu extra"] },
        { id: "i2", qty: 2, name: "Rolinho primavera", subtotal: 16 },
      ],
      subtotal: 112,
      deliveryFee: 10,
      total: 122,
      payment: { method: "presencial", presentialMethod: "dinheiro", changeFor: 150, paid: false },
      address: { street: "Rua Augusta", number: "2200", neighborhood: "Cerqueira César", reference: "Prédio comercial, recepção" },
      disposables: true,
      status: "em_rota",
      courierId: "c1",
      deliveryStage: "no_local",
    },
    {
      id: "ord_c3f0468",
      createdAt: ago(38),
      channel: "balcao",
      balcaoMode: "entrega",
      customerName: "Bruno Alves",
      customerPhone: "(11) 98022-6671",
      items: [
        { id: "i1", qty: 1, name: "Marmita fit", subtotal: 28, variation: ["Média"] },
        { id: "i2", qty: 1, name: "Suco verde", subtotal: 14 },
        { id: "i3", qty: 1, name: "Marmita tradicional", subtotal: 22.8 },
      ],
      subtotal: 64.8,
      deliveryFee: 6,
      total: 70.8,
      payment: { method: "presencial", presentialMethod: "debito", paid: true },
      address: { street: "Rua Cardeal Arcoverde", number: "310", neighborhood: "Pinheiros" },
      disposables: false,
      status: "em_rota",
      courierId: "c2",
      deliveryStage: "proxima",
    },
    {
      id: "ord_0e1f467",
      createdAt: ago(44),
      channel: "delivery",
      customerName: "Paulo Henrique",
      customerPhone: "(11) 91234-5678",
      items: [{ id: "i1", qty: 2, name: "Poke salmão", subtotal: 76, variation: ["Grande"] }],
      subtotal: 76,
      deliveryFee: 8,
      total: 84,
      payment: { method: "pix", paid: true },
      address: { street: "Rua Oscar Freire", number: "900", neighborhood: "Jardins" },
      disposables: true,
      status: "em_rota",
      courierId: "c2",
      deliveryStage: "na_fila",
    },
    {
      id: "ord_4b5c461",
      createdAt: ago(70),
      channel: "mesa",
      tableNumber: 5,
      items: [
        { id: "i1", qty: 2, name: "Prato executivo", subtotal: 68, variation: ["Peixe"] },
        { id: "i2", qty: 2, name: "Suco de laranja", subtotal: 20 },
      ],
      subtotal: 88,
      deliveryFee: 0,
      total: 88,
      payment: { method: "cartao_online", paid: true },
      status: "finalizado",
    },
    {
      id: "ord_6d7e458",
      createdAt: ago(95),
      channel: "delivery",
      customerName: "Letícia",
      customerPhone: "(11) 95555-1010",
      items: [{ id: "i1", qty: 1, name: "Pizza Calabresa", subtotal: 58, variation: ["Média"] }],
      subtotal: 58,
      deliveryFee: 8,
      total: 66,
      payment: { method: "pix", paid: true },
      address: { street: "Rua Frei Caneca", number: "40", neighborhood: "Consolação" },
      status: "finalizado",
      courierId: "c1",
      deliveryStage: "entregue",
    },
    {
      id: "ord_8f9a455",
      createdAt: ago(120),
      channel: "balcao",
      balcaoMode: "avulso",
      items: [{ id: "i1", qty: 1, name: "Sanduíche natural", subtotal: 18 }],
      subtotal: 18,
      deliveryFee: 0,
      total: 18,
      payment: { method: "presencial", presentialMethod: "dinheiro", paid: false },
      notes: "Cliente desistiu do pedido.",
      status: "cancelado",
    },
  ];
};
